/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wangxi_jnid_JNITest */

#ifndef _Included_com_example_wangxi_jnid_JNITest
#define _Included_com_example_wangxi_jnid_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wangxi_jnid_JNITest
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wangxi_jnid_JNITest_accessField
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_accessStaticField
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_accessMethod
        (JNIEnv *,jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_accessStaticMethod
        (JNIEnv *,jobject);
#ifdef __cplusplus
}
#endif
#endif
