/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wangxi_jnid_JNITest */

#ifndef _Included_com_example_wangxi_jnid_JNITest
#define _Included_com_example_wangxi_jnid_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wangxi_jnid_JNITest
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wangxi_jnid_JNITest_accessField
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_accessStaticField
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_accessMethod
        (JNIEnv *,jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_accessStaticMethod
        (JNIEnv *,jobject,jstring);

JNIEXPORT jobject JNICALL Java_com_example_wangxi_jnid_JNITest_accessConstructor
        (JNIEnv *,jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_accessNonvirtualMethod
        (JNIEnv *,jobject);

JNIEXPORT jstring JNICALL Java_com_example_wangxi_jnid_JNITest_chineseChars
        (JNIEnv *,jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_giveArray
        (JNIEnv *,jobject,jintArray t);

JNIEXPORT jintArray JNICALL Java_com_example_wangxi_jnid_JNITest_getArray
        (JNIEnv *,jobject,jint len);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_localRef
        (JNIEnv *,jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_createGlobalRef
        (JNIEnv *,jobject);

JNIEXPORT jstring JNICALL Java_com_example_wangxi_jnid_JNITest_getGlobalRef
        (JNIEnv *,jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_deleteGlobalRef
        (JNIEnv *,jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_exception
        (JNIEnv *,jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_cached
        (JNIEnv *,jobject);

JNIEXPORT void JNICALL Java_com_example_wangxi_jnid_JNITest_initIds
        (JNIEnv *env, jclass jcls);
#ifdef __cplusplus
}
#endif
#endif
